// fallback-data.js – curated fallback movies for different industries
// Each entry includes a language code to help filter by industry.

export const FALLBACK_DATA = {
  hollywood: [
    {
      id: 1001,
      title: "Inception",
      overview: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
      vote_average: 8.4,
      popularity: 96,
      release_date: "2010-07-15",
      genre_ids: [28, 878, 12],
      poster_path: "/udckMyTJCQ2I7kgVZmhU0Q9I3k1.jpg",
      backdrop_path: "/s3TBrRGB1iav7gFOCNx3H31MoES.jpg",
      language: "en",
      source: "fallback"
    },
    {
      id: 1002,
      title: "The Dark Knight",
      overview: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
      vote_average: 8.5,
      popularity: 98,
      release_date: "2008-07-16",
      genre_ids: [28, 80, 18],
      poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
      backdrop_path: "/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg",
      language: "en",
      source: "fallback"
    },
    {
      id: 1003,
      title: "The Shawshank Redemption",
      overview: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
      vote_average: 8.7,
      popularity: 95,
      release_date: "1994-09-23",
      genre_ids: [18, 80],
      poster_path: "/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
      backdrop_path: "/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
      language: "en",
      source: "fallback"
    },
    {
      id: 1004,
      title: "The Godfather",
      overview: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
      vote_average: 8.7,
      popularity: 90,
      release_date: "1972-03-14",
      genre_ids: [18, 80],
      poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
      backdrop_path: "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
      language: "en",
      source: "fallback"
    },
    {
      id: 1005,
      title: "Pulp Fiction",
      overview: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
      vote_average: 8.5,
      popularity: 85,
      release_date: "1994-09-10",
      genre_ids: [80, 18],
      poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
      backdrop_path: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
      language: "en",
      source: "fallback"
    },
    {
      id: 1006,
      title: "Forrest Gump",
      overview: "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate and other historical events unfold through the perspective of an Alabama man with an IQ of 75.",
      vote_average: 8.5,
      popularity: 82,
      release_date: "1994-06-23",
      genre_ids: [35, 18, 10749],
      poster_path: "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
      backdrop_path: "/7c9UVPPiGTltqRUsHLnBbg6ZM0Z.jpg",
      language: "en",
      source: "fallback"
    },
    {
      id: 1007,
      title: "The Matrix",
      overview: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
      vote_average: 8.2,
      popularity: 91,
      release_date: "1999-03-30",
      genre_ids: [28, 878],
      poster_path: "/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
      backdrop_path: "/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg",
      language: "en",
      source: "fallback"
    },
    {
      id: 1008,
      title: "Fight Club",
      overview: "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.",
      vote_average: 8.4,
      popularity: 87,
      release_date: "1999-10-15",
      genre_ids: [18, 53],
      poster_path: "/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
      backdrop_path: "/hZkgoQYus5vegHoetLkqzbPPOwA.jpg",
      language: "en",
      source: "fallback"
    },
    {
      id: 1009,
      title: "Interstellar",
      overview: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
      vote_average: 8.4,
      popularity: 97,
      release_date: "2014-11-05",
      genre_ids: [12, 18, 878],
      poster_path: "/gEU2QniL6C8zB6fX0nQq9X0qZD4.jpg",
      backdrop_path: "/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
      language: "en",
      source: "fallback"
    },
    {
      id: 1010,
      title: "Goodfellas",
      overview: "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito.",
      vote_average: 8.5,
      popularity: 75,
      release_date: "1990-09-12",
      genre_ids: [18, 80],
      poster_path: "/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
      backdrop_path: "/sw7mordbZxgITU877yTpZCud90M.jpg",
      language: "en",
      source: "fallback"
    },
    {
      id: 1011,
      title: "Titanic",
      overview: "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
      vote_average: 7.9,
      popularity: 89,
      release_date: "1997-11-18",
      genre_ids: [18, 10749],
      poster_path: "/9xjZS2rlVxm8SI9bX6xJy0hW0LU.jpg",
      backdrop_path: "/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg",
      language: "en",
      source: "fallback"
    },
    {
      id: 1012,
      title: "Avatar",
      overview: "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
      vote_average: 7.9,
      popularity: 94,
      release_date: "2009-12-10",
      genre_ids: [28, 12, 878],
      poster_path: "/t5K7V9E2PhzqNjJjV1lLlaSGO4d.jpg",
      backdrop_path: "/t88mRkhDDL7LiCjdS5L1cj4A5XW.jpg",
      language: "en",
      source: "fallback"
    },
    {
      id: 1013,
      title: "Avengers: Endgame",
      overview: "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more.",
      vote_average: 8.4,
      popularity: 99,
      release_date: "2019-04-24",
      genre_ids: [28, 878, 12],
      poster_path: "/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
      backdrop_path: "/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
      language: "en",
      source: "fallback"
    },
    {
      id: 1014,
      title: "Jurassic Park",
      overview: "A pragmatic paleontologist touring an almost complete theme park on an island in Central America is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose.",
      vote_average: 8.1,
      popularity: 83,
      release_date: "1993-05-20",
      genre_ids: [12, 878, 28],
      poster_path: "/oU7Ohr2fJhiXKkMl2p9K9wKoD2.jpg",
      backdrop_path: "/phv1K3uJ3iYW4ImK1y0YJY4J6mq.jpg",
      language: "en",
      source: "fallback"
    },
    {
      id: 1015,
      title: "Star Wars: A New Hope",
      overview: "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle-station.",
      vote_average: 8.2,
      popularity: 89,
      release_date: "1977-05-25",
      genre_ids: [12, 28, 878],
      poster_path: "/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
      backdrop_path: "/zqkmTZz50w8U8SpDBEkzOlLkjuO.jpg",
      language: "en",
      source: "fallback"
    },
    {
      id: 1016,
      title: "The Lord of the Rings: The Fellowship of the Ring",
      overview: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
      vote_average: 8.4,
      popularity: 88,
      release_date: "2001-12-18",
      genre_ids: [12, 14, 28],
      poster_path: "/6oom5QYQ2yQTMJIbnvbkF9y2L6L.jpg",
      backdrop_path: "/pIUvQ9Ed35wlWhY2oU6OmwEsmzG.jpg",
      language: "en",
      source: "fallback"
    },
    {
      id: 1017,
      title: "Gladiator",
      overview: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
      vote_average: 8.2,
      popularity: 84,
      release_date: "2000-05-01",
      genre_ids: [28, 18, 12],
      poster_path: "/ty8TGr0MTauHmxH0gqnI5wT1Ajh.jpg",
      backdrop_path: "/7cXMTbJchV3kN6hKhV4oW2EuS6X.jpg",
      language: "en",
      source: "fallback"
    },
    {
      id: 1018,
      title: "The Silence of the Lambs",
      overview: "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.",
      vote_average: 8.3,
      popularity: 72,
      release_date: "1991-02-14",
      genre_ids: [80, 18, 53],
      poster_path: "/rplLJ2hPcOQmkFhTqUte0MkEaO2.jpg",
      backdrop_path: "/exnA9C3E3L0L1fO3g2I2v5h0Z1T.jpg",
      language: "en",
      source: "fallback"
    },
    {
      id: 1019,
      title: "Se7en",
      overview: "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
      vote_average: 8.4,
      popularity: 80,
      release_date: "1995-09-22",
      genre_ids: [80, 18, 53],
      poster_path: "/6yoghtyTpznpBik8EngEmJskVUO.jpg",
      backdrop_path: "/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg",
      language: "en",
      source: "fallback"
    },
    {
      id: 1020,
      title: "Saving Private Ryan",
      overview: "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.",
      vote_average: 8.2,
      popularity: 78,
      release_date: "1998-07-24",
      genre_ids: [18, 36, 10752],
      poster_path: "/uqx37cS8cpHg8U35f9U5IBlrCV3.jpg",
      backdrop_path: "/4EJyCBrL7Y0U8M6i2dL5k3pNiT.jpg",
      language: "en",
      source: "fallback"
    }
  ],
  bollywood: [
    {
      id: 2001,
      title: "3 Idiots",
      overview: "Two friends are searching for their long lost companion. They revisit their college days and recall the time they spent with their friend who inspired them to think differently.",
      vote_average: 8.5,
      popularity: 85,
      release_date: "2009-12-25",
      genre_ids: [35, 18],
      poster_path: "/66A9MqXOyVFCssoloscw79z8Tew.jpg",
      backdrop_path: "/dMtgBYkMmFMTgEBYKnvMtqex0G.jpg",
      language: "hi",
      source: "fallback"
    },
    {
      id: 2002,
      title: "Dangal",
      overview: "Former wrestler Mahavir Singh Phogat trains his daughters Geeta and Babita to become world-class wrestlers.",
      vote_average: 8.3,
      popularity: 78,
      release_date: "2016-12-21",
      genre_ids: [18, 28],
      poster_path: "/jLiA1WW3kL1K9lYfYmVj57RD74N.jpg",
      backdrop_path: "/jLiA1WW3kL1K9lYfYmVj57RD74N.jpg",
      language: "hi",
      source: "fallback"
    },
    {
      id: 2003,
      title: "Dilwale Dulhania Le Jayenge",
      overview: "When Raj meets Simran in Europe, it isn't love at first sight but when Simran moves to India for an arranged marriage, Raj follows her, expressing his love.",
      vote_average: 8.2,
      popularity: 80,
      release_date: "1995-10-20",
      genre_ids: [35, 18, 10749],
      poster_path: "/2CAL2433ZeIihfX1Hb2139CX0pW.jpg",
      backdrop_path: "/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg",
      language: "hi",
      source: "fallback"
    },
    {
      id: 2004,
      title: "Lagaan",
      overview: "The villagers of a small British Indian reserve challenge a playing field match against an arrogant British officer, hoping to avoid the punitive tax.",
      vote_average: 8.1,
      popularity: 72,
      release_date: "2001-06-15",
      genre_ids: [18, 35, 28],
      poster_path: "/yNX9lFRAFeNLNRIXdqZK9gYrYKa.jpg",
      backdrop_path: "/76VwduxQMkVXOUktps85dE0lLeP.jpg",
      language: "hi",
      source: "fallback"
    },
    {
      id: 2005,
      title: "Sholay",
      overview: "Two criminals are hired by a village chief to help get rid of a gang of dacoits.",
      vote_average: 8.1,
      popularity: 75,
      release_date: "1975-08-15",
      genre_ids: [28, 18, 80],
      poster_path: "/ya9bwgqA4eNl5bQ9QqS0jcmRoBS.jpg",
      backdrop_path: "/8aYAfAPolsRFrHbP1rafeSgg2Ew.jpg",
      language: "hi",
      source: "fallback"
    },
    {
      id: 2006,
      title: "Mughal-e-Azam",
      overview: "A poor young prince falls in love with a court dancer and battles to marry her.",
      vote_average: 8.0,
      popularity: 65,
      release_date: "1960-08-18",
      genre_ids: [18, 10749],
      poster_path: "/8GyHL4TftI4SKVA8Jj9JpthhIu6.jpg",
      backdrop_path: "/8GyHL4TftI4SKVA8Jj9JpthhIu6.jpg",
      language: "hi",
      source: "fallback"
    },
    {
      id: 2007,
      title: "Bajrangi Bhaijaan",
      overview: "A man with a saintly persona and an innocent outlook, sets out on a journey to help a mute Pakistani girl reach her destination.",
      vote_average: 7.8,
      popularity: 70,
      release_date: "2015-07-17",
      genre_ids: [18, 35, 28],
      poster_path: "/vhlliI7HZZlWfo5d6CiyfBAGLrW.jpg",
      backdrop_path: "/n9QCm8uagvmXH476u5qFQsW8HkU.jpg",
      language: "hi",
      source: "fallback"
    },
    {
      id: 2008,
      title: "PK",
      overview: "An alien on Earth loses the only device he can use to communicate with his spaceship. His confusion becomes the source of many psychological complexities.",
      vote_average: 7.7,
      popularity: 68,
      release_date: "2014-12-19",
      genre_ids: [35, 878, 18],
      poster_path: "/z2x2Y4tncefsIU7h82gmUM5vnBJ.jpg",
      backdrop_path: "/z2x2Y4tncefsIU7h82gmUM5vnBJ.jpg",
      language: "hi",
      source: "fallback"
    },
    {
      id: 2009,
      title: "My Name is Khan",
      overview: "A man with a rare neurological disorder wants to make a difference in the world.",
      vote_average: 7.7,
      popularity: 62,
      release_date: "2010-02-12",
      genre_ids: [18, 10749],
      poster_path: "/6bnOhhrrrq6RZhMgz4aGyqbJ9Wf.jpg",
      backdrop_path: "/6bnOhhrrrq6RZhMgz4aGyqbJ9Wf.jpg",
      language: "hi",
      source: "fallback"
    },
    {
      id: 2010,
      title: "Chak De! India",
      overview: "A former hockey player coaches the Indian women's national hockey team to win a gold medal.",
      vote_average: 7.8,
      popularity: 65,
      release_date: "2007-08-10",
      genre_ids: [18, 28],
      poster_path: "/OjJ2eZFMr0InHxjYCQXwxDoo4v.jpg",
      backdrop_path: "/OjJ2eZFMr0InHxjYCQXwxDoo4v.jpg",
      language: "hi",
      source: "fallback"
    },
    {
      id: 2011,
      title: "Gully Boy",
      overview: "A young street rapper from Mumbai tries to become a major music artist.",
      vote_average: 7.6,
      popularity: 58,
      release_date: "2019-02-14",
      genre_ids: [18, 80],
      poster_path: "/iM5NcqoSs3qzDAe5AKW8PQD42n0.jpg",
      backdrop_path: "/iM5NcqoSs3qzDAe5AKW8PQD42n0.jpg",
      language: "hi",
      source: "fallback"
    },
    {
      id: 2012,
      title: "Kabir Singh",
      overview: "A surgeon goes into a self-destructive downward spiral after his lover marries another man.",
      vote_average: 7.2,
      popularity: 60,
      release_date: "2019-06-21",
      genre_ids: [18, 10749],
      poster_path: "/73QoFJFmUrJfDG2EynFjNc5gJxk.jpg",
      backdrop_path: "/73QoFJFmUrJfDG2EynFjNc5gJxk.jpg",
      language: "hi",
      source: "fallback"
    },
    {
      id: 2013,
      title: "Raazi",
      overview: "A spy is sent to India to investigate a political secret and falls in love with her target.",
      vote_average: 7.8,
      popularity: 55,
      release_date: "2018-05-11",
      genre_ids: [18, 53],
      poster_path: "/wMO5XGq2ybhL3CdCEPJ8OXWbNZG.jpg",
      backdrop_path: "/wMO5XGq2ybhL3CdCEPJ8OXWbNZG.jpg",
      language: "hi",
      source: "fallback"
    },
    {
      id: 2014,
      title: "Andhadhun",
      overview: "A piano player who gets embroiled in a crime learns that the truth isn't always what it seems.",
      vote_average: 7.9,
      popularity: 52,
      release_date: "2018-02-10",
      genre_ids: [53, 9648, 18],
      poster_path: "/dy3K6hNvwE05siGgiLJcEiwgpdO.jpg",
      backdrop_path: "/dy3K6hNvwE05siGgiLJcEiwgpdO.jpg",
      language: "hi",
      source: "fallback"
    },
    {
      id: 2015,
      title: "Tumbbad",
      overview: "A story about a cursed warehouse and the family that built it.",
      vote_average: 7.8,
      popularity: 48,
      release_date: "2018-10-12",
      genre_ids: [27, 18, 14],
      poster_path: "/7SRFyxMZFIAfAWtmD4x3L5kvPzj.jpg",
      backdrop_path: "/7SRFyxMZFIAfAWtmD4x3L5kvPzj.jpg",
      language: "hi",
      source: "fallback"
    },
    {
      id: 2016,
      title: "Drishyam",
      overview: "A man tries to protect his family after a murder takes place.",
      vote_average: 7.7,
      popularity: 50,
      release_date: "2015-07-31",
      genre_ids: [53, 18],
      poster_path: "/xiDGcXJTvu1lazFRYip6g1eLt9c.jpg",
      backdrop_path: "/xiDGcXJTvu1lazFRYip6g1eLt9c.jpg",
      language: "hi",
      source: "fallback"
    },
    {
      id: 2017,
      title: "Uri: The Surgical Strike",
      overview: "Indian army special forces execute a covert operation to strike Pakistani posts.",
      vote_average: 7.8,
      popularity: 54,
      release_date: "2019-01-11",
      genre_ids: [28, 18, 53],
      poster_path: "/yNySAgpAnWmPpYinim9E0tUzJWG.jpg",
      backdrop_path: "/yNySAgpAnWmPpYinim9E0tUzJWG.jpg",
      language: "hi",
      source: "fallback"
    },
    {
      id: 2018,
      title: "War",
      overview: "An Indian secret agent is assigned to capture a rogue intelligence officer.",
      vote_average: 6.8,
      popularity: 52,
      release_date: "2019-10-02",
      genre_ids: [28, 53, 80],
      poster_path: "/9LO8CPHeRE3bmAeAuMAkAMOyiF2.jpg",
      backdrop_path: "/9LO8CPHeRE3bmAeAuMAkAMOyiF2.jpg",
      language: "hi",
      source: "fallback"
    },
    {
      id: 2019,
      title: "Housefull 4",
      overview: "A reincarnation comedy about lovers from 1910 and modern times.",
      vote_average: 5.6,
      popularity: 45,
      release_date: "2019-10-18",
      genre_ids: [35, 14, 878],
      poster_path: "/yepUC6RZUyAN5Gc0B2pGWAL7lDD.jpg",
      backdrop_path: "/yepUC6RZUyAN5Gc0B2pGWAL7lDD.jpg",
      language: "hi",
      source: "fallback"
    },
    {
      id: 2020,
      title: "Dilwale",
      overview: "A man and a woman are in love, but their parents are sworn enemies.",
      vote_average: 5.5,
      popularity: 42,
      release_date: "2015-12-18",
      genre_ids: [35, 18, 10749],
      poster_path: "/doAzav9kfdtsoSdw1MDFvjKq3J4.jpg",
      backdrop_path: "/doAzav9kfdtsoSdw1MDFvjKq3J4.jpg",
      language: "hi",
      source: "fallback"
    }
  ],
  nepali: [
    {
      id: 3001,
      title: "Kagbeni",
      overview: "A suspense thriller about a man who discovers a mysterious box that grants wishes, but at a terrible price.",
      vote_average: 7.2,
      popularity: 30,
      release_date: "2008-05-02",
      genre_ids: [9648, 53],
      poster_path: "",
      backdrop_path: "",
      language: "ne",
      source: "fallback"
    },
    {
      id: 3002,
      title: "Pashupati Prasad",
      overview: "A heart-warming drama about a young man who comes to Kathmandu looking for a job and faces life's challenges.",
      vote_average: 8.0,
      popularity: 45,
      release_date: "2016-09-02",
      genre_ids: [18, 35],
      poster_path: "",
      backdrop_path: "",
      language: "ne",
      source: "fallback"
    },
    {
      id: 3003,
      title: "Classmates",
      overview: "The story of a group of students in Kathmandu who are on the verge of their SLC exams.",
      vote_average: 7.5,
      popularity: 40,
      release_date: "2010-09-03",
      genre_ids: [18, 35],
      poster_path: "",
      backdrop_path: "",
      language: "ne",
      source: "fallback"
    },
    {
      id: 3004,
      title: "White Mountain",
      overview: "A story about the beauty of Nepal's mountains and the people who live in them.",
      vote_average: 7.0,
      popularity: 25,
      release_date: "2014-03-21",
      genre_ids: [18, 12],
      poster_path: "",
      backdrop_path: "",
      language: "ne",
      source: "fallback"
    },
    {
      id: 3005,
      title: "God Tires",
      overview: "A comedy film about the unexpected journey of a man and his vehicle.",
      vote_average: 6.8,
      popularity: 28,
      release_date: "2012-08-31",
      genre_ids: [35, 18],
      poster_path: "",
      backdrop_path: "",
      language: "ne",
      source: "fallback"
    },
    {
      id: 3006,
      title: "Soal",
      overview: "A suspense thriller involving a missing person and a mysterious phone call.",
      vote_average: 6.5,
      popularity: 22,
      release_date: "2015-02-13",
      genre_ids: [53, 9648],
      poster_path: "",
      backdrop_path: "",
      language: "ne",
      source: "fallback"
    },
    {
      id: 3007,
      title: "Chakra",
      overview: "A romantic drama about two young people who face obstacles in their relationship.",
      vote_average: 6.4,
      popularity: 20,
      release_date: "2017-03-10",
      genre_ids: [18, 10749],
      poster_path: "",
      backdrop_path: "",
      language: "ne",
      source: "fallback"
    },
    {
      id: 3008,
      title: "Mero Euta Sano Chhewang",
      overview: "A story about a small boy who dreams of becoming a hero.",
      vote_average: 6.2,
      popularity: 18,
      release_date: "2018-04-06",
      genre_ids: [10751, 18],
      poster_path: "",
      backdrop_path: "",
      language: "ne",
      source: "fallback"
    },
    {
      id: 3009,
      title: "Bulbul",
      overview: "A tragic love story set in the beautiful hills of Nepal.",
      vote_average: 6.3,
      popularity: 15,
      release_date: "2019-03-22",
      genre_ids: [18, 10749],
      poster_path: "",
      backdrop_path: "",
      language: "ne",
      source: "fallback"
    },
    {
      id: 3010,
      title: "Aaya",
      overview: "A horror film about a haunted house and the secrets it holds.",
      vote_average: 5.8,
      popularity: 12,
      release_date: "2016-10-28",
      genre_ids: [27, 53],
      poster_path: "",
      backdrop_path: "",
      language: "ne",
      source: "fallback"
    },
    {
      id: 3011,
      title: "Lukamari",
      overview: "A romantic comedy about a couple who meet in an unexpected way.",
      vote_average: 6.0,
      popularity: 16,
      release_date: "2017-09-15",
      genre_ids: [35, 10749],
      poster_path: "",
      backdrop_path: "",
      language: "ne",
      source: "fallback"
    },
    {
      id: 3012,
      title: "Kabaddi Kabaddi",
      overview: "A comedy film about a kabaddi team and their journey to victory.",
      vote_average: 6.1,
      popularity: 14,
      release_date: "2015-08-21",
      genre_ids: [35, 28],
      poster_path: "",
      backdrop_path: "",
      language: "ne",
      source: "fallback"
    },
    {
      id: 3013,
      title: "Sano Saibaba",
      overview: "A comedy about a small-town boy who becomes a movie star.",
      vote_average: 5.9,
      popularity: 11,
      release_date: "2018-09-07",
      genre_ids: [35, 18],
      poster_path: "",
      backdrop_path: "",
      language: "ne",
      source: "fallback"
    },
    {
      id: 3014,
      title: "Dhana",
      overview: "An action drama about a man seeking revenge for his father's death.",
      vote_average: 5.5,
      popularity: 10,
      release_date: "2019-05-03",
      genre_ids: [28, 53],
      poster_path: "",
      backdrop_path: "",
      language: "ne",
      source: "fallback"
    },
    {
      id: 3015,
      title: "Parcha",
      overview: "A political drama about corruption and justice in Nepal.",
      vote_average: 5.4,
      popularity: 9,
      release_date: "2017-11-10",
      genre_ids: [18, 80],
      poster_path: "",
      backdrop_path: "",
      language: "ne",
      source: "fallback"
    },
    {
      id: 3016,
      title: "Mero Haat Ma",
      overview: "A romantic story about two childhood friends who reunite after years.",
      vote_average: 6.2,
      popularity: 17,
      release_date: "2016-02-14",
      genre_ids: [18, 10749],
      poster_path: "",
      backdrop_path: "",
      language: "ne",
      source: "fallback"
    },
    {
      id: 3017,
      title: "Mero Naam Nepal",
      overview: "A patriotic film about the love for one's country.",
      vote_average: 5.7,
      popularity: 8,
      release_date: "2019-07-01",
      genre_ids: [18, 28],
      poster_path: "",
      backdrop_path: "",
      language: "ne",
      source: "fallback"
    },
    {
      id: 3018,
      title: "Maya",
      overview: "A love story set in the beautiful landscapes of Nepal.",
      vote_average: 6.1,
      popularity: 13,
      release_date: "2015-06-05",
      genre_ids: [18, 10749],
      poster_path: "",
      backdrop_path: "",
      language: "ne",
      source: "fallback"
    },
    {
      id: 3019,
      title: "Chino",
      overview: "A story about a boy's journey to find his missing father.",
      vote_average: 5.7,
      popularity: 8,
      release_date: "2019-08-16",
      genre_ids: [18, 12],
      poster_path: "",
      backdrop_path: "",
      language: "ne",
      source: "fallback"
    },
    {
      id: 3020,
      title: "Fulpikar",
      overview: "A romantic drama about two lovers who face societal obstacles.",
      vote_average: 5.8,
      popularity: 7,
      release_date: "2020-02-07",
      genre_ids: [18, 10749],
      poster_path: "",
      backdrop_path: "",
      language: "ne",
      source: "fallback"
    }
  ]
};